# -*- coding: utf-8 -*-
"""Bike Sharing_Dicoding_Subbmission.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HLJzRAFAufV4QvwTdDSMANfOSxTZtLhr

# Proyek Analisis Data: [Bike Sharing - Hour]
- **Nama:** Akbar Muhammad Prakoso
- **Email:** akbar.muhammt@gmail.com
- **ID Dicoding:** [Input Username]

## Menentukan Pertanyaan Bisnis

- Pertanyaan 1
  Apakah terdapat pola musiman dalam penggunaan sepeda (count) berdasarkan jam atau musim?
- Pertanyaan 2
  Bagaimana hubungan antara temperatur dan kepadatan penggunaan sepeda (count) setiap jam? Apakah ada tren yang jelas?

## Import Semua Packages/Library yang Digunakan
"""

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

# Langkah 1: Gathering Data
# Upload file "hour.csv"
uploaded = files.upload()

"""### Assessing Data"""

# Langkah 2: Assessing Data
# Membaca file CSV menjadi DataFrame
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

# Menampilkan informasi singkat tentang dataset
print("Informasi Dataset:")
print(df.info())

# Menampilkan beberapa baris pertama dari dataset
print("\nBeberapa Baris Pertama Dataset:")
print(df.head())

# Mengecek nilai yang hilang (missing values)
missing_values = df.isnull().sum()
print("\nJumlah Missing Values per Kolom:")
print(missing_values)

# Memeriksa tipe data untuk setiap kolom
print("\nTipe Data untuk Setiap Kolom:")
print(df.dtypes)

"""### Cleaning Data"""

# Langkah 3: Cleaning Data
# Tidak ada data cleaning yang diperlukan dalam contoh ini karena dataset bersih.

# Konversi kolom 'dteday' menjadi tipe data datetime
df['dteday'] = pd.to_datetime(df['dteday'])

"""## Exploratory Data Analysis (EDA)

### Explore ...
"""

# Langkah 4: Exploratory Data Analysis (EDA)
# Distribusi Data
plt.figure(figsize=(15, 10))
sns.set(style="whitegrid")
sns.boxplot(data=df[['temp', 'atemp', 'hum', 'windspeed']])
plt.title('Distribusi Data Variabel Numerik')
plt.xlabel('Variabel')
plt.ylabel('Nilai')
plt.show()

# Korelasi antar fitur numerik
plt.figure(figsize=(12, 8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Korelasi antar Fitur Numerik')
plt.show()

# Distribusi data untuk setiap kolom kategorikal
plt.figure(figsize=(12, 8))
sns.countplot(data=df, x='season', palette='coolwarm')
plt.title('Distribusi Data untuk Kolom Kategorikal (Musim)')
plt.xlabel('Musim')
plt.ylabel('Jumlah Data')
plt.show()

# Melihat tren penggunaan sepeda seiring waktu
plt.figure(figsize=(12, 8))
sns.lineplot(data=df, x='dteday', y='cnt')
plt.title('Tren Penggunaan Sepeda Seiring Waktu')
plt.xlabel('Tanggal')
plt.ylabel('Jumlah Peminjaman Sepeda')
plt.show()

"""## Visualization & Explanatory Analysis

### Pertanyaan 1: Pola musiman dalam penggunaan sepeda (count) berdasarkan jam atau musim
"""

# Menghitung jumlah rata-rata penggunaan sepeda (count) per jam dalam sehari
hourly_count = df.groupby('hr')['cnt'].mean()
hourly_count

# Visualisasi pertanyaan bisnis 1
plt.figure(figsize=(10, 6))
hourly_count.plot(kind='line', marker='o', color='skyblue')
plt.title('Average Bike Usage per Hour')
plt.xlabel('Hour')
plt.ylabel('Average Count')
plt.xticks(range(24))
plt.grid(True)
plt.show()

print("Hasil Analisis Pertanyaan Bisnis 1:")
print("---------------------------------------------------")
print("Pola musiman dalam penggunaan sepeda (count) berdasarkan jam:")
for hour, count in hourly_count.items():
    print(f"Jam {hour}: Rata-rata penggunaan sepeda = {count:.2f}")
print("---------------------------------------------------")

"""### Pertanyaan 2: Hubungan antara temperatur dan kepadatan penggunaan sepeda (count) setiap jam"""

# Visualisasi scatter plot antara kolom 'temp' dan 'cnt'
plt.figure(figsize=(10, 6))
plt.scatter(df['temp'], df['cnt'], alpha=0.5)
plt.title('Temperature vs Bike Usage')
plt.xlabel('Temperature')
plt.ylabel('Count')
plt.show()

correlation = df['temp'].corr(df['cnt'])

print("\nHasil Analisis Pertanyaan Bisnis 2:")
print("---------------------------------------------------")
print("Hubungan antara temperatur dan kepadatan penggunaan sepeda (count) setiap jam:")
print(f"Korelasi antara temperatur dan penggunaan sepeda: {correlation:.2f}")
if correlation > 0:
    print("Terdapat korelasi positif antara temperatur dan penggunaan sepeda.")
elif correlation < 0:
    print("Terdapat korelasi negatif antara temperatur dan penggunaan sepeda.")
else:
    print("Tidak ada korelasi antara temperatur dan penggunaan sepeda.")
print("---------------------------------------------------")

"""## Conclusion

#### Conclution pertanyaan 1
**Pertanyaan Bisnis 1: Pola Musiman dalam Penggunaan Sepeda (Count) Berdasarkan Jam**

Berdasarkan hasil analisis pertanyaan bisnis 1, kita dapat menyimpulkan pola musiman dalam penggunaan sepeda (count) berdasarkan jam sebagai berikut:

* Penggunaan sepeda (count) cenderung rendah pada jam-jam awal pagi (00:00 - 05:00) dengan rata-rata di bawah 20.
* Jumlah penggunaan sepeda mulai meningkat seiring berjalannya waktu setelah jam 06:00, mencapai puncaknya pada jam 17:00 (5:00 PM) dengan rata-rata lebih dari 450.
* Setelah jam 17:00, penggunaan sepeda mulai menurun secara bertahap hingga larut malam.
Hal ini menunjukkan adanya pola musiman dalam penggunaan sepeda, dengan puncak penggunaan terjadi pada sore hari dan jumlah penggunaan yang lebih rendah pada jam-jam awal pagi dan larut malam.

#### Conclution pertanyaan 2
**Pertanyaan Bisnis 2: Hubungan antara Temperatur dan Kepadatan Penggunaan Sepeda (Count) Setiap Jam**
Berdasarkan hasil analisis pertanyaan bisnis 2, kita dapat menyimpulkan tentang hubungan antara temperatur dan kepadatan penggunaan sepeda (count) setiap jam sebagai berikut:

* **Korelasi**: Terdapat korelasi positif antara temperatur dan penggunaan sepeda dengan nilai korelasi sebesar 0.40. Hal ini menunjukkan bahwa semakin tinggi suhu, semakin tinggi juga kepadatan penggunaan sepeda.
* **Interpretasi Korelasi**: Korelasi positif yang signifikan menunjukkan bahwa ketika suhu meningkat, jumlah penggunaan sepeda juga cenderung meningkat. Hal ini dapat diinterpretasikan sebagai penggunaan sepeda yang lebih tinggi saat cuaca lebih hangat atau pada hari-hari musim panas.

Dengan demikian, dapat disimpulkan bahwa suhu memiliki pengaruh yang positif terhadap penggunaan sepeda, dan analisis ini memberikan wawasan tambahan tentang faktor-faktor yang mempengaruhi pola penggunaan sepeda.
"""